# This is the TOML config file for project: go_build_web

[package]
name = "todo_server"
version = "0.1"
authors = ["Todo Server Ltd."]
build_opts = ["-race"]
deps = [
    "github.com/julienschmidt/httprouter"
]

[assets]
url_prefix = "/assets"
image_exts = ["png", "jpg", "jpeg"]
deps = [
    "react@0.12.2",
    "reflux",
    "todomvc-common",
]

    [[assets.vendor_set]]
    name = "vendor-react"
    requires = ["react/addons", "reflux"]

    [[assets.entry]]
    name = "todo_app"
    externals = ["vendor-react"]

[distribution]
build_opts = []
cross_targets = [
    ["darwin", "amd64"],
]