# This is the TOML config file for project: todo_server

[package]
name = "todo_server"
version = "0.1"
authors = ["Todo Server Ltd."]
build_opts = ["-race"]
is_graceful = true
deps = [
    "github.com/julienschmidt/httprouter"
]

[assets]
url_prefix = "/assets"
assets_mapping_json = "assets_map.json"
assets_mapping_pkg = "main"
image_exts = [".png", ".jpg", ".jpeg"]
deps = [
    "react@0.12.2",
    "reflux",
    "todomvc-common",
]

    [[assets.vendor_set]]
    name = "vendor-react"
    requires = ["react/addons", "reflux"]

    [[assets.entry]]
    name = "todo_app"
    externals = ["vendor-react"]

[distribution]
build_opts = []
pack_extras = ["project.toml"]
cross_targets = [
    ["linux", "amd64"],
]
