# This is the TOML config file for project: go_build_web

[package]
name = "todo_server"
version = "0.1"
authors = ["Todo Server Ltd."]
build_opts = ["-race"]
deps = [
    "github.com/julienschmidt/httprouter"
]

[assets]
deps = [
    "react",
    "reflux"
]